name: Flutter CI iOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.4'

      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS (simulator)
        run: flutter build ios --debug --simulator

      # To build for physical device (requires code signing setup):
      # - name: Build iOS (release)
      #   run: flutter build ipa --release